name: Pure LED Solutions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76229
title: Pure LED Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfdfc'
    - '#b5b7c3'
    - '#050701'
    - '#273114'
    - '#717881'
  brandStrength: 0.5
  lightness: 0.5050853029824793
  saturation: 0.6233887085691094
  rhythmicContrast: 0.7266640479210764
purpose: []
